name: Copilot Maintenance Delegate

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull request number to delegate to @copilot"
        required: true
      instructions:
        description: "Optional extra guidance for the Copilot agent"
        required: false
        default: ""
  check_suite:
    types:
      - completed

permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
        working-directory: .github/scripts
      - name: Post manual delegation comment
        run: node .github/scripts/maintenance-delegate-manual.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PR_NUMBER: ${{ inputs.pr_number }}
          INPUT_INSTRUCTIONS: ${{ inputs.instructions }}

  automatic:
    if: github.event_name == 'check_suite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
        working-directory: .github/scripts
      - name: Delegate failed workflow run to Copilot
        run: node .github/scripts/maintenance-delegate-check-suite.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
