name: Fork Main Sync

on:
  workflow_dispatch:
    inputs:
      watchChecks:
        description: 'Wait for PR checks to finish before exiting'
        required: false
        default: 'true'
      enableAutoMerge:
        description: 'Enable auto-merge when PR checks pass'
        required: false
        default: 'true'
  schedule:
    - cron: '15 2 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync fork main via PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WATCH_PR_CHECKS: ${{ inputs.watchChecks == 'false' && '0' || '1' }}
          ENABLE_AUTO_MERGE: ${{ inputs.enableAutoMerge == 'false' && '0' || '1' }}
        run: ./script/sync-fork-main-pr.sh

      - name: Upload rebase log
        if: failure() && env.REBASE_LOG_PATH != ''
        uses: actions/upload-artifact@v4
        with:
          name: rebase-log
          path: ${{ env.REBASE_LOG_PATH }}
          if-no-files-found: ignore

      - name: Append job summary
        if: always()
        run: |
          {
            echo "### Fork Main Sync"
            echo ""
            echo "* Outcome: ${SYNC_OUTCOME:-unknown}"
            if [[ -n "${PR_URL:-}" ]]; then
              echo "* PR: ${PR_URL}"
            fi
            if [[ -n "${REBASE_LOG_PATH:-}" ]]; then
              echo "* Rebase log: ${REBASE_LOG_PATH}"
            fi
          } >>"$GITHUB_STEP_SUMMARY"
